### ISSUE TITLE
Integrierbarer USB Hub

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/rpi_radio#10]
Wie können wir die USB-Geräte intern über einen aktiven Hub anschliessen?

**Comment by Andreasvonow** [comment]
Der USB2640 Chip ist ein 2:1 USB Hub mit SD Card Interface. Plan wäre vom zweiteh USB des Raspberry ein USB Kabek zum Hub zu legen. Das heisst aber, dass wir Model B brauchen, weil wir ja an einem USB den WLAN Stick haben.

**Comment by dbrgn** [comment]
Refs #7

**Comment by Andreasvonow** [comment]
Es gibt noch eine weitere Option: 
Wir schliessen an den zwei USBs des Raspberry zwei Hubs an. Das macht dann 4 USB + 2 SD Card Slots. Einen USB brauchen wir dann für WLAN und der Rest bleibt frei für Memorysticks etc.

**Comment by dbrgn** [comment]
Ah, das wär relativ cool. Die USB Hubs sind nicht teuer, oder?

Wie läuft das mit der Stromversorgung? Haben die genug Strom um Stromhungrige USB-Devices zu betreiben? (Ich glaube die USB Ports auf dem RPI sind separat abgesichert, oder?)

**Comment by Andreasvonow** [comment]
Jeder USB Port kann mindestens 1A liefern.  Bei Überlast (ca. 1.1 ... 1.5A) schaltet er ab. 
So ein Hub kostet schon ein paar Franken, ich kann den Preis aber erst Rechnern, wenn das Schema fertig ist.
Es sind wahscheinlich für ca. 10 .. 12 Franken Bauteil drauf plus PCB.

---

Andreas von Ow

Haldenholz 5
8340 Hinwil
Switzerland

Email: andreas@vonow.eu

-------- Ursprüngliche Nachricht --------
Von: Danilo Bargen notifications@github.com 
Datum: 06.06.2013  23:00  (GMT+01:00) 
An: dbrgn/rpi_radio rpi_radio@noreply.github.com 
Cc: Andreasvonow andreas@vonow.biz 
Betreff: Re: [rpi_radio] Integrierbarer USB Hub (#10) 

Ah, das wär relativ cool. Die USB Hubs sind nicht teuer, oder?

Wie läuft das mit der Stromversorgung? Haben die genug Strom um Stromhungrige USB-Devices zu betreiben? (Ich glaube die USB Ports auf dem RPI sind separat abgesichert, oder?)

**Comment by dbrgn** [comment]
Auf der anderen Seite kostet uns das Model B auch 10-12 Franken mehr. D.h. für den selben Preis haben wir dann doppelt so viele Ports.

Ich würde sagen go for it...

**Comment by cfaessler** [comment]
Finde ich auch gut!
Ein paar vorige Ports sind sicher nicht verkehrt

-------- Ursprüngliche Nachricht --------
Von: Danilo Bargen notifications@github.com
Datum:
An: dbrgn/rpi_radio rpi_radio@noreply.github.com
Cc: "Faessler Christian (cfaessle@hsr.ch)" cfaessle@hsr.ch
Betreff: Re: [rpi_radio] Integrierbarer USB Hub (#10)

Auf der anderen Seite kostet uns das Model B auch 10-12 Franken mehr. D.h. für den selben Preis haben wir dann doppelt so viele Ports.

Ich würde sagen go for it...
