### ISSUE TITLE
SD Card Slots

### ISSUE THREAD

**Issue by cfaessler** [dbrgn/rpi_radio#13]
Für mich würde auch ein Slot reichen, wenn das einfacher zu machen wäre.

**Comment by dbrgn** [comment]
Ja, wenns die Hardware vereinfacht reicht ein Slot definitiv. Zwei wären aber schon nett.

**Comment by Andreasvonow** [comment]
Der Chip den ich gefunden habe, kann leider nur ein SD Card. HW seitig ist dieser Chip ziemlich optimal, weil auch gleich der USB HUB drin ist. ... und der Chip ist einfach erhältlich.

**Comment by cfaessler** [comment]
Dann bin ich für diesen Chip! 1 Slot ist für mich auch i.o

**Comment by dbrgn** [comment]
Alright! :) Ich denke man kann dieses Ticket in dem Fall schliessen?
