### ISSUE TITLE
WLAN Stick Evaluation

### ISSUE THREAD

**Issue by cfaessler** [dbrgn/rpi_radio#14]

**Comment by dbrgn** [comment]
Ich würde sagen die Kandidaten sind:
- TP-Link TL-WN725N (19 CHF, 150 Mbit/s) https://www.digitec.ch/ProdukteDetails2.aspx?Reiter=Bilder&Artikel=260888
- ZyXEL NWD-2105 (16.90 CHF, 150 MBit/s) http://www.pi-shop.ch/zyxel-nwd-2105-mini-wlan-n-usb-stick
- ZyXEL NWD-2205 (24.90 CHF, 300 MBit/s) http://www.pi-shop.ch/zyxel-nwd-2205-mini-wlan-n-usb-stick

**Comment by cfaessler** [comment]
Jep, kann ja eigentlich auch gut individuell sein. Mit dem Zyxel hatte ich bis jetzt noch nie Probleme

**Comment by dbrgn** [comment]
Stimmt auch wieder. Die Frage ist, welchen wir bei den "Bestellungen" dazu tun.

**Comment by cfaessler** [comment]
obsolete with raspberry pi 3 :)
