### ISSUE TITLE
LCD Evaluation

### ISSUE THREAD

**Issue by cfaessler** [dbrgn/rpi_radio#15]
Wie wärs mit einem TFT http://shop.boxtec.ch/screen-module-itdb02-p-40304.html + Coppler http://imall.iteadstudio.com/im130425001.html.
Da gäbe es auch libs dafür: http://henningkarlsen.com/electronics/library.php?id=52 obs einen Port für python gibt weiss ich nicht, könnt ich mir aber vorstellen. Einen SPI Treiber gibt es: http://valdodov.com/index.php?show=hardware
In einer ersten Phase können wir ja auch da Character orientiert arbeiten ohne Grafik.
Interessante Diskussion dazu http://www.raspberrypi.org/phpBB3/viewtopic.php?f=64&t=33679

**Comment by Andreasvonow** [comment]
Sieht gar nicht schlecht aus, vor allem zu dem Preis. Wenn wir die Tasten auf den Touchscreen legen, wäre das natürlich eine gute Lösung. Ich weiss nicht genau, wie wir den das Diplay ansteuern wollen, der Raspberry hat keine 16Bit Bus aber evtl. geht es mit 8Bit oder über SPI.

**Comment by cfaessler** [comment]
Vielleicht schaff ich mir ein solches Ding an und spiele mal etwas rum.
Ich denke in die Treiberentwicklung müsste man doch einiges an Arbeit stecken. Vielleicht doch eher was für V2.0.
Bzw. wie weit seht ihr den Zeithorizont für den ersten Prototypen?

**Comment by cfaessler** [comment]
https://github.com/notro/fbtft/wiki/LCD-Modules
https://github.com/notro/fbtft/wiki
https://code.google.com/p/itdb02/

**Comment by Andreasvonow** [comment]
Alles klar, werde am Sa oder So auch ein pdf generieren. 
Wenn es für das "richtige" LCD noch zu früh ist, könnte ich mir eine Lösung mit den Displays von EA und HW Tasten vorstellen. Es sollte möglich sein sowohl das Textdisplay (4x20 Char) mit 4Bit Interface wie auch ein monochromes 128x64 Pixel Grafikdisplay mit SPI zu unterstützen. Der Gehäuseausschnitt für die Anzeige ist dabei allerdings nicht genau gleich. Sobald wir uns über Display, Tasten und das Design geeinigt haben, lege ich mit dem Display Board los. Da wir aber nicht mehrere HW Iterationen machen wollen, nehme ich mir dafür genügend Zeit. Das PCB könnte vielleicht Anfang/Mitte Juli bestellt werden und ein Prototyp wäre evtl. Ende Juli bereit. Ist das für euch ok?

Gruss
Andy

---

Andreas von Ow

andreas@vonow.eu
+41 44 938 12 61

Am 30.05.2013 um 23:27 schrieb Christian Fässler notifications@github.com:

**Comment by dbrgn** [comment]
Ich wär nach wie vor für ein traditionelles CharLCD, aber wenn das PCB beide Typen unterstützt, dann umso besser.

Der Zeitplan sieht für mich gut aus.

**Comment by dbrgn** [comment]
-> EA DogL 128.
