### ISSUE TITLE
Bedienung

### ISSUE THREAD

**Issue by Andreasvonow** [dbrgn/rpi_radio#16]
Wir müssen uns überlegen welche Bedienelemente wir brauchen und wie wir sie anordnen. Mein Vorschlag:

Taste 1: Previous
Taste 2: Play/Pause
Taste 3: Next
Taste 4: Power On/Off

Rotary Encoder 1: Scrollen / Auswählen

Potentiometer 1: Volume

Weitere Bedienelemente können auf dem Touchscreen implementiert werden.

**Comment by dbrgn** [comment]
Einverstanden!

**Comment by cfaessler** [comment]
Finde ich auch gut so!

-------- Ursprüngliche Nachricht --------
Von: Andreasvonow notifications@github.com
Datum:
An: dbrgn/rpi_radio rpi_radio@noreply.github.com
Betreff: [rpi_radio] Bedienung (#16)

Wir müssen uns überlegen welche Bedienelemente wir brauchen und wie wir sie anordnen. Mein Vorschlag:

Taste 1: Previous
Taste 2: Play/Pause
Taste 3: Next
Taste 4: Power On/Off

Rotary Encoder 1: Scrollen / Auswählen

Potentiometer 1: Volume

Weitere Bedienelemente können auf dem Touchscreen implementiert werden.

**Comment by dbrgn** [comment]
Entschieden gemäss Gehäuse-Meeting.
