### ISSUE TITLE
Display wählen

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/rpi_radio#5]
Unser Test-LCD:
![Bild LCD](http://i.imgur.com/FrUwHU1.jpg)
http://mikroshop.ch/LED_LCD.html?gruppe=7&artikel=84

Gibt es ein brauchbares Char-LCD mit dem HD44780 controller ohne den dicken Rahmen?

Alternativ ein Grafik-LCD?

**Comment by Andreasvonow** [comment]
Die Diplays von Electronic Assembly, DOG Serie haben keinen Rahmen. Es gibt Text- (4x20 Zeichen) und Grafikdisplays (128x64 Pixel, optional mit Touch), sie sind allerdings nicht pinkompatibel, das PCB könnte aber für beide Typen ausgelegt werden. 
Alternative ist aber auch das 3.2" LCD von Chrigi. Das ist zwar mechanisch etwas schwieriger einzubauen, bietet aber fast unbegrenzte Möglichkeiten (vorausgesetzt man findet ein gutes Interface zu den RPI GPIOs).

**Comment by dbrgn** [comment]
Die EA CharLCDs sind HD44780 kompatibel, oder?

**Comment by Andreasvonow** [comment]
Ja, die Text-Displays sind HD44780 kompatibel. Es werden 3 versch. Modi zur Ansteuerung unterstützt, 8Bit, 4Bit und seriell über SPI. Die Grafik-Displays verwenden einen anderen Controller und können nur seriell angesteuert werden.

---

Andreas von Ow

Haldenholz 5
8340 Hinwil
Switzerland

Email: andreas@vonow.eu

-------- Ursprüngliche Nachricht --------
Von: Danilo Bargen notifications@github.com 
Datum: 03.06.2013  10:47  (GMT+01:00) 
An: dbrgn/rpi_radio rpi_radio@noreply.github.com 
Cc: Andreasvonow andreas@vonow.biz 
Betreff: Re: [rpi_radio] Display wählen (#5) 

Die EA CharLCDs sind HD44780 kompatibel, oder?

**Comment by dbrgn** [comment]
Duplikat von #15.
